### ISSUE TITLE
Thread Count - keep increase

### ISSUE THREAD

**Issue by rezamusthafa** [bluedenim/log4j-s3-search#109]
Thanks for the fantastic module, but after trying to implement it, thread count keeps increasing, do you have any ideas to handle this case? Thank you

![Screenshot from 2021-09-15 13-46-50](https://user-images.githubusercontent.com/70500626/133545746-85ffd1b7-cb85-4f77-b5ea-a4777a2117b5.png)

**Comment by bluedenim** [comment]
Hello. I'll need more information about your use case in order to investigate further. 

First of all, what version are you using?
Is this a web app?
Can you send me a copy of your log4j configuration file?
Also: are you able to do a thread dump when this count is high?

I'll look into the code to see if I can find anything suspicious. However, the investigation will be much easier and faster if I have more info. 

Thanks!

**Comment by bluedenim** [comment]
Can you check to see if release 3.6.0 fixed this?
