### ISSUE TITLE
Support AWS IRSA.

### ISSUE THREAD

**Issue by davinchia** [bluedenim/log4j-s3-search#140]
Hi @bluedenim !

Thanks again for the great plugin. We at Airbyte love this. I'm wondering if you know whether this plugin [supports IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).  

We have several OSS community members interested in getting this working: https://github.com/airbytehq/airbyte-platform/pull/263. I'm not sure if IRSA works well with this plugin now, and I would prefer to contribute back than roll our own.

We are happy to take pointers & submit a contribution.

Thanks!

**Comment by bluedenim** [comment]
I'll look into it.

**Comment by bluedenim** [comment]
I looked at the conversation you cited. The S3 access key and secret key are indeed optional. In fact, it's safer to not use them but instead use the IAM roles set up for your processes. 

There was a question of whether they can be blank. Currently setting them to blank certainly will not work because the code only checks for `null `and not blanks. If for some reason your setup needs to set them to blank (e.g. for some backward compatibility), https://github.com/bluedenim/log4j-s3-search/blob/90317ec6efbd666d7230d9fdcac265921e044171/appender-core/src/main/java/com/van/logging/aws/AwsClientHelpers.java#L16 can be amended to use https://github.com/bluedenim/log4j-s3-search/blob/90317ec6efbd666d7230d9fdcac265921e044171/appender-core/src/main/java/com/van/logging/utils/StringUtils.java#L15 instead.

**Comment by bluedenim** [comment]
Anyway. from the conversation, it looks like this is not an actual issue for your setup; I believe there was a confusion over whether the `s3AwsKey `and `s3AwsSecret `properties were required. 

Let me know if this is not the case.
