### ISSUE TITLE
Multipart S3 upload support

### ISSUE THREAD

**Issue by anks14** [bluedenim/log4j-s3-search#39]
Is it possible to minimise number of S3 files being created for logs by using Multipart Upload somehow? since S3 doesn't allow direct concatenation of small files?

**Comment by bluedenim** [comment]
Not sure. But I think large uploads are chunked by the AWS SDK, so uploading a large file should be fine. In fact, I think storing large files is one of the reasons ppl use S3 for.

As far as this project is concerned, I think you can tweak either the `stagingBufferSize` or `stagingBufferAge` (if using time-based batching) to be a large value so that uploads are done less frequently and with a larger payload.
