### ISSUE TITLE
 Error processing element Log4j2Appender ([Appenders: null]): CLASS_NOT_FOUND

### ISSUE THREAD

**Issue by nikhithareddy-modak** [bluedenim/log4j-s3-search#88]
I have added the therealvan dependencies in my JAVA project pom.xml ,I have build the jar and ran the code,then I got the error 

2020-11-20 14:48:54,581 main ERROR Error processing element Log4j2Appender ([Appenders: null]): CLASS_NOT_FOUND
2020-11-20 14:48:54,757 main ERROR Unable to locate appender "Log4j2Appender" for logger config "<package>"
2020-11-20 14:48:54,758 main ERROR Unable to locate appender "Log4j2Appender" for logger config "<package>"

I have used all the versions including the latest version 2.8.3

**Comment by bluedenim** [comment]
I think it's just a configuration issue. Here's a sample project that should get you started:

[log4j2.zip](https://github.com/bluedenim/log4j-s3-search/files/5580638/log4j2.zip)

**Comment by bluedenim** [comment]
Here's how to exercise it after expanding:
```
cd <where log4j2.zip was expanded>
mvn install

cd target
java -cp log4j-s3-search-log4j2-sample.jar example.App
```

**Comment by nikhithareddy-modak** [comment]
Can you please explain the sentence "Exclude all the transitive dependencies to external libs so we get to specify the versions we want ", that you have written in pom.xml

**Comment by bluedenim** [comment]
Sure. So when I built appender-core, for example, I used `com.amazonaws:aws-java-sdk:1.11.613` (see https://github.com/bluedenim/log4j-s3-search/blob/master/pom.xml#L46-L50). 

So if you don't change anything, when you depend on `com.therealvan:appender-log4j2:2.8.3`, it depends on `com.therealvan:appender-core:2.8.3`, and that depends on `com.amazonaws:aws-java-sdk:1.11.613`. So the transitive dependency of your program now includes `com.amazonaws:aws-java-sdk:1.11.613.` 

When I do this:
```
                <exclusion>
                    <groupId>com.amazonaws</groupId>
                    <artifactId>aws-java-sdk-s3</artifactId>
                </exclusion>
```

It removes `com.amazonaws:aws-java-sdk:1.11.613` from your final project. This will allow you to now add the version of `com.amazonaws:aws-java-sdk-s3` **that you want**. Maybe you want a newer version of AWS S3 SDK than 1.11.613. Instead of waiting for me to update my library, you can:

* Add the exclude above, then
* Add the dependency to the version of AWS S3 you want (maybe 1.11.907) in your pom.xml


https://www.educba.com/maven-exclude-dependency/ explains it better if you want details.

**Comment by nikhithareddy-modak** [comment]
Thank you! My issue got solved it was because of not using latest dependencies of log4j2 and also for not included maven shade plugin in pom.xml
